### ISSUE TITLE
Problems with parentheses in search results

### ISSUE THREAD

**Issue by circumeo** [alfonmga/mui-docs-alfred-workflow#1]
<img width="778" alt="스크린샷 2024-01-27 오후 7 02 58" src="https://github.com/alfonmga/mui-docs-alfred-workflow/assets/76243664/73c3f48f-d834-4322-8f5c-c71469bd240e">

I'm using the workflow I uploaded well
First of all, thank you!
The results come out as shown in the picture above, is there a solution?

**Comment by exwyezed** [comment]
Hey @circumeo, thank you for letting me know about this issue.

It's now fixed. I've released a [new version, `v1.0.3`, of the Alfred Workflow](https://github.com/alfonmga/mui-docs-alfred-workflow/releases/tag/v1.0.3).

Best,
Alfon.
